/* Automatically generated by './build/bin/build-entry.js' */

import CmsPanel from './Panel/index.vue'

const components = [
  CmsPanel
]
const install = function (Vue) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

// module.exports = {
//   version: '0.0.1',
//   CmsPanel
// }

// module.exports.default = module.exports
